services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=player
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: always

volumes:
  config-volume: